name = input("What's your name? ")
print("Hello," , name )
print(type(name))
count = input("How many Data Centers are present in NV region?")
print(type(count))
count = int(count)
print(type(count))
pi = input("What's the value of pi? ")
print(type(pi))
pi = float(pi)
print(type(pi))
